version: 1.0.0.{build}
configuration: Release
platform: x86
install:
- git submodule init
- git submodule update
build:
  project: FileOpenerformClipboard.sln
  verbosity: minimal
artifacts:
- path: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
  name: FileOpenerFromClipboard_Stable
deploy:
- provider: GitHub
  tag: Release-v$(appveyor_build_version)
  release: 
  auth_token:
    secure: FZGlOzjXOlI70ZNfll82No7ADk6X0UClnOhb3xoiRm9UEnTpFI3L3zDfNNdW357L
  artifact: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
