version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: >-
    git submodule init

    git submodule update
build:
  project: FileOpenerformClipboard.sln
  verbosity: minimal
artifacts:
- path: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
  name: FileOpenerFromClipboard_Stable
deploy:
- provider: GitHub
  tag: FileOpnerFromClipBoard-v$(appveyor_build_version)
  release: FileOpnerFromClipBoard-v$(appveyor_build_version)
  description: description
  auth_token:
    secure: FZGlOzjXOlI70ZNfll82No7ADk6X0UClnOhb3xoiRm9UEnTpFI3L3zDfNNdW357L
  artifact: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
  draft: false
  prerelease: false
  on:
    branch: /master/