version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: >-
    git submodule init

    git submodule update

    nuget restore
build:
  project: FileOpenerformClipboard.sln
  verbosity: minimal
artifacts:
- path: FileOpenerFromClipboardGui\bin\Release\*.exe
  name: exe
- path: FileOpenerFromClipboardGui\bin\Release\*.dll
  name: dll
deploy:
- provider: GitHub
  tag: FileOpnerFromClipBoard-v$(appveyor_build_version)
  release: FileOpnerFromClipBoard-v$(appveyor_build_version)
  description: auto build
  auth_token:
    secure: c8dDXg/WHIulAFj/46zWb0bo3rLqir6l3DH8uHZas4yB+mxvBQBjLeTi9EFmxswZ
  artifact: /.*\.(exe|dll)/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: /master/
