version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: >-
    git submodule init

    git submodule update

    nuget restore
build:
  project: FileOpenerformClipboard.sln
  verbosity: minimal
before_deploy:
- cmd: >-
    cd FileOpenerFromClipboardGui\bin\Release

    del *.pdb

    del *.config
deploy:
- provider: GitHub
  tag: FileOpnerFromClipBoard-v$(appveyor_build_version)
  release: FileOpnerFromClipBoard-v$(appveyor_build_version)
  description: auto build
  auth_token:
    secure: c8dDXg/WHIulAFj/46zWb0bo3rLqir6l3DH8uHZas4yB+mxvBQBjLeTi9EFmxswZ
  artifact: FileOpenerFromClipboardGui\bin\Release\*
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: /master/