version: 1.0.1.{build}
skip_tags: true
configuration: Release
platform: x86
install:
- git submodule init
- git submodule update
build:
  project: FileOpenerformClipboard.sln
  verbosity: minimal
artifacts:
- path: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
  name: FileOpenerFromClipboard_Stable
deploy:
- provider: GitHub
  tag: FileOpenerFromClipboard-v$(appveyor_build_version)
  release: FileOpenerFromClipboard-v$(appveyor_build_version)
  description: Release時の説明
  auth_token:
    secure: FZGlOzjXOlI70ZNfll82No7ADk6X0UClnOhb3xoiRm9UEnTpFI3L3zDfNNdW357L
  artifact: FileOpenerformClipboard\bin\Release\FileOpenerformClipboard.exe
  draft: false
  prerelease: false
  on:
    branch: /master/
